apiVersion: v1
kind: ServiceAccount
metadata:
  name: todo-app-sa
  namespace: production
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::175076060567:role/todo-app-rds-secret-read-Role
  labels:
    app: todo-app
    environment: production